# Generated by Django 4.2 on 2023-04-24 20:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import utils.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('subject_id', models.CharField(max_length=124)),
                ('learning_area', models.CharField(max_length=100)),
                ('week', models.IntegerField()),
                ('country', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_start_date', models.DateField()),
                ('mid_term_break', models.DateField()),
                ('term_end_date', models.DateField()),
                ('term_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=150)),
                ('academic_term', models.CharField(max_length=124)),
                ('academic_year', models.CharField(default=1900, max_length=4)),
                ('weeks', models.IntegerField()),
                ('months', models.IntegerField()),
                ('exam_start_date', models.DateField(blank=True, null=True)),
                ('exam_end_date', models.DateField(blank=True, null=True)),
                ('other_events', models.CharField(blank=True, max_length=124, null=True)),
                ('event_start_date', models.DateField(blank=True, null=True)),
                ('event_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('year_established', models.DateField()),
                ('motto', models.CharField(max_length=255)),
                ('total_students', models.IntegerField()),
                ('total_teachers', models.IntegerField(blank=True, null=True)),
                ('principal_name', models.CharField(max_length=124)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('website_url', models.URLField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=124)),
                ('country', models.CharField(max_length=124)),
                ('description', models.CharField(max_length=512)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=utils.helper.get_file_path)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to=utils.helper.get_file_path)),
                ('term_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='school.term')),
            ],
        ),
    ]
